Add redux
andytai7/Buildingblocks pull request #1
Opened 2020-11-28 10:51 UTC by austinkwok1997

2020-11-29 21:05 UTC, anthonylopes54 commented on src/components/Landing.js
> +    if (loggedIn === null || loggedIn == false) {
if (!loggedIn)

2020-11-29 21:10 UTC, anthonylopes54 commented on src/components/Landing.js
> -            return (
You can delete this comment

2020-11-29 21:13 UTC, anthonylopes54 commented on src/components/LoginWithEmail.js
> +    // function constructor(props) {
Delete comments

2020-11-29 21:22 UTC, anthonylopes54 commented on src/components/LoginWithEmail.js
> +                    dispatch({ type: "CHANGE_LOGGEDIN", loggedIn: true });
Do you think it would be better to put this into one big dispatch call instead of having so many lines of code?

2020-11-29 21:22 UTC, anthonylopes54 commented on src/components/LoginWithEmail.js
> +                    // localStorage.setItem('loggedIn', true);
Remove comments

2020-11-29 21:25 UTC, anthonylopes54 commented on src/components/LoginWithEmail.js
> +    if (loggedIn === null || loggedIn === false) {
if (!loggedIn)

2020-11-29 21:29 UTC, anthonylopes54 commented on src/components/OuterChatContainer.js
> +    if (chatroom === false) {
Use a ternary expression: return !chatroom ? _____ : ______ ;

2020-11-29 21:30 UTC, anthonylopes54 commented on src/components/Sidebar.js
> -const SideBar = (props) => {
👍

2020-11-29 21:46 UTC, anthonylopes54 commented on src/components/DashboardHeaderChat.js
> +      <p className="chatRoomName">{lastUser}</p>
Is lastUser the chatroom? I don't recall.

2020-11-29 21:47 UTC, anthonylopes54 commented on src/components/ChildComponent.js
> +const ChildComponent = () => {
What is this file? Maybe leave a comment or change the name of it?

2020-11-29 21:47 UTC, anthonylopes54 commented on src/components/AnotherChildComponent.js
> +const AnotherChildComponent = () => {
What is this file? Maybe leave a comment or change the name of it?

2020-11-29 21:48 UTC, anthonylopes54 commented on src/Reducers/User.js
> +    switch (action.type) {
Create a case for updating the whole user so we don't have to make so many function calls when they log in.

2020-11-29 21:49 UTC, anthonylopes54 commented on src/Reducers/Reducer.js
> +const Reducer = (state = initState, action) => {
Why do we have two reducer files?

2020-11-29 21:50 UTC, anthonylopes54 reviewed
Nice job! Just wanted to make sure... have you tested all the new functionality?

2020-11-29 21:51 UTC, anthonylopes54 requested changes
Left a few comments

2020-12-04 23:39 UTC, rrashi commented
i made the suggested changes with austin expect one. he'll take care of that.

2020-12-07 06:45 UTC, austinkwok1997 commented
> 
> 
> Nice job! Just wanted to make sure... have you tested all the new functionality?

@anthonylopes54 I focused mostly on redux for this branch. There are definitely bugs currently in the app, but I believe it'll be easier for the team to address them on their own separate branches.

2020-12-13 08:36 UTC, austinkwok1997 commented
I believe we have finished all the suggested changes. @anthonylopes54

2020-12-22 18:31 UTC, anthonylopes54 commented
> I believe we have finished all the suggested changes. @anthonylopes54

Thanks Austin, sorry for the late reply on this. I'll approve. Have you tested all the Redux functionality? If so, go ahead and squash and merge, else test everything first.

2020-12-22 18:32 UTC, anthonylopes54 approved these changes

2020-12-23 22:09 UTC, merged